# Generated by Django 2.0.7 on 2019-09-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rollno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
